sudo: false

language: erlang
otp_release: 17.5

branches:
    only:
        - master


matrix:
    include:
        - otp_release: 18.0

addons:
    apt:
        packages:
            - libexpat1-dev

install: make compile
script: make test

cache:
    directories:
        - dialyzer
